# Используем официальный образ Java
FROM openjdk:17-jdk-slim

# Рабочая директория внутри контейнера
WORKDIR /app

# Копируем собранный JAR-файл сервера
COPY server/target/server.jar server.jar

# Команда для запуска сервера
CMD ["java", "-jar", "server.jar"]